server:
  port: 8096

spring:
  application:
    name: exchange-system
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/exchange_db?useUnicode=true&useSSL=false&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      name: DruidDataSource
      initial-size: 1
      min-idle: 1
      max-active: 20
      async-init: true
      max-wait: 6000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      max-evictable-idle-time-millis: 900000
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      connection-init-sqls: SET NAMES utf8mb4 COLLATE utf8mb4_0900_ai_ci;
      filters: stat
  redis:
    host: 127.0.0.1
    port: 6379
    password: 01star
    database: 0
    # Redisson 连接池配置
    redisson:
      connection-pool-size: 64
      idle-connection-timeout: 10000
      connect-timeout: 10000
      timeout: 3000

# Web3j 配置
web3j:
  node-url: https://eth-sepolia.g.alchemy.com/v2/eh_dEB9V7MnEnkpfNh5xq
  network-id: 11155111
  private-key: c20eea3133007bbf18c1b2221029695e9ba385930864e8c2f5e7489e2c3d9ec3
  gas-price: 20000000000
  gas-limit: 4000000
  ens:
    enabled: false  # 禁用ENS解析

# JWT 配置
jwt:
  secret: mySecretKeyForJwtTokenGenerationAndValidation123456
  expiration: 604800000  # 7 天（毫秒）

# 合约地址配置
contract:
  exchange:
    address: '0xD29A830C4CfC0D9fF017Fbb14B572a9a2F9b2930'
  exth:
    address: '0xD74347dE964F59f40d55761e9e1e82aBB57F7533'
  usdt:
    address: '0xaCc2AAC99533e857fBC7091821E74465cE019806'
  rnb:
    address: '0x2797CB961104B32e81EE2E3E559433f9dB141aD3'
  gbp:
    address: '0x1FCD9dbC44862dD83d395C8386A1e850A0C488e9'
  treasure:
    address: '0x42D15000E8A7dCBA6a9416960864F3dD46Be2fE9'
  dao:
    address: '0xB5168879C3A8b71DD4645C22465D5f9106df433d'
  timelock:
    address: '0xFd2F6B0467adb7a140c7a6ff0cB701EA3dA39e87'
  airdrop:
    address: '0x0894c5c63D6239241945e502b86F82ab5a4E3A52'

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

