server:
  port: 8096

spring:
  application:
    name: exchange-system
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/exchange_db?useUnicode=true&useSSL=false&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      name: DruidDataSource
      initial-size: 1
      min-idle: 1
      max-active: 20
      async-init: true
      max-wait: 6000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      max-evictable-idle-time-millis: 900000
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      connection-init-sqls: SET NAMES utf8mb4 COLLATE utf8mb4_0900_ai_ci;
      filters: stat
  redis:
    host: 127.0.0.1
    port: 6379
    password: 01star
    database: 0
    # Redisson 连接池配置
    redisson:
      connection-pool-size: 64
      idle-connection-timeout: 10000
      connect-timeout: 10000
      timeout: 3000

# Web3j 配置
web3j:
  node-url: https://eth-sepolia.g.alchemy.com/v2/eh_dEB9V7MnEnkpfNh5xq
  network-id: 11155111
  private-key: c20eea3133007bbf18c1b2221029695e9ba385930864e8c2f5e7489e2c3d9ec3
  gas-price: 20000000000
  gas-limit: 4000000
  ens:
    enabled: false  # 禁用ENS解析

# 合约地址配置
contract:
  exchange:
    address: '0xFCdC9D1F41788E8d00Ca1E32c6EC7313fa412218'
  exth:
    address: '0x74F203A8Dc287E3fAad70f8D99809A2A0ea8Bc4c'
  usdt:
    address: '0x03083414ae29Ea92a098019d5761942825f292F0'
  rnb:
    address: '0x3abf3Fb46313ECb3DB43ca634559515B0D4e75B7'
  gbp:
    address: '0x6AFdD0c3E613af3C04FF947D8023D11bE0eC762E'
  treasure:
    address: '0x71D2DD419c809Af15B5a2BB0309331Bf44B179db'
  dao:
    address: '0x19Ee005eca986c310A428Ff918dA9cCe54d1B942'
  timelock:
    address: '0x200c10e57b73a1a3a14c1388657Df870bBe35961'
  airdrop:
    address: '0x518f79b5581BdbDb7C0E175604Cd59d86612Fc45'
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

